# Generated by Django 4.2.30 on 2026-04-11 20:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_lead_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader_name', models.CharField(blank=True, max_length=100)),
                ('work_stream', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_codebase', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='WikiLink',
            fields=[
                ('wikki_id', models.AutoField(primary_key=True, serialize=False)),
                ('wikki_description', models.CharField(max_length=255)),
                ('wikki_link', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_links', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('role_title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='StandupInfo',
            fields=[
                ('standup_id', models.AutoField(primary_key=True, serialize=False)),
                ('standup_time', models.TimeField()),
                ('standup_link', models.URLField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standup_info', to='core.team')),
            ],
            options={
                'verbose_name_plural': 'Standup Info',
            },
        ),
        migrations.CreateModel(
            name='RepositoryLink',
            fields=[
                ('repo_id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_url', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_links', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_subject', models.CharField(max_length=255)),
                ('message_body', models.TextField()),
                ('message_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], max_length=10)),
                ('message_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('platform_type', models.CharField(choices=[('teams', 'Microsoft Teams'), ('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('in_person', 'In Person')], max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('agenda_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dependency_id', models.AutoField(primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], max_length=20)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='core.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='core.team')),
            ],
            options={
                'verbose_name_plural': 'Dependencies',
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('email', 'Email')], max_length=20)),
                ('channel_value', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_channels', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='BoardLink',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_type', models.CharField(max_length=50)),
                ('board_url', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_links', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('action_changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField()),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
