# Generated by Django 6.0.4 on 2026-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lead_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='tech_tags',
            field=models.TextField(blank=True, help_text='Comma separated tags'),
        ),
    ]
