# Generated by Django 6.0.4 on 2026-04-16 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timetrack_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentVote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.department')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'department')},
            },
        ),
    ]
