# Generated by Django 6.0.4 on 2026-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departmentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g. Web Development, Cloud Infrastructure', max_length=150, null=True),
        ),
    ]
