# Generated by Django 6.0.4 on 2026-04-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorylink',
            name='team',
        ),
        migrations.RemoveField(
            model_name='standupinfo',
            name='team',
        ),
        migrations.RemoveField(
            model_name='timetrack',
            name='team',
        ),
        migrations.RemoveField(
            model_name='wikilink',
            name='team',
        ),
        migrations.DeleteModel(
            name='BoardLink',
        ),
        migrations.DeleteModel(
            name='RepositoryLink',
        ),
        migrations.DeleteModel(
            name='StandupInfo',
        ),
        migrations.DeleteModel(
            name='TimeTrack',
        ),
        migrations.DeleteModel(
            name='WikiLink',
        ),
    ]
