# Generated by Django 6.0.4 on 2026-04-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_repositorylink_team_remove_standupinfo_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLink',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_type', models.CharField(max_length=50)),
                ('board_url', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_links', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryLink',
            fields=[
                ('repo_id', models.AutoField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_url', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_links', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='StandupInfo',
            fields=[
                ('standup_id', models.AutoField(primary_key=True, serialize=False)),
                ('standup_time', models.TimeField()),
                ('standup_link', models.URLField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standup_info', to='core.team')),
            ],
            options={
                'verbose_name_plural': 'Standup Info',
            },
        ),
        migrations.CreateModel(
            name='TimeTrack',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracks', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='WikiLink',
            fields=[
                ('wikki_id', models.AutoField(primary_key=True, serialize=False)),
                ('wikki_description', models.CharField(max_length=255)),
                ('wikki_link', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_links', to='core.team')),
            ],
        ),
    ]
