# Generated by Django 6.0.4 on 2026-04-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_boardlink_repositorylink_standupinfo_timetrack_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTrack',
        ),
    ]
