# Generated by Django 6.0.4 on 2026-04-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_timetrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentVote',
        ),
    ]
