# Generated by Django 6.0.4 on 2026-04-20 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_departmentvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role_title',
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
