# Generated by Django 6.0.4 on 2026-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_teammember_email_remove_teammember_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=50),
        ),
    ]
