# Generated by Django 6.0.4 on 2026-04-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_team_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
