# Generated by Django 6.0.4 on 2026-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teammember_unique_user_per_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, help_text='Job title or role e.g. Senior Engineer, QA Engineer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
