# Generated by Django 6.0.4 on 2026-04-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_role_to_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, default='', help_text='e.g. Lead Engineer, Product Owner', max_length=100),
        ),
    ]
